SU-SWS/stanford_basic

css/base/base.css
templates/block/block--search-form-block.html.twig
templates/block/block--system-branding-block.html.twig

- Waiting on mobile menu to be completed before finalizing responsiveness
- Updates template files for lockup and search so that they appear inline
- This PR works in partnership with another (noted below) in stanford_mrc
- End of sprint (3/15)
- N/A
1. Pull this branch
2. Pull branch of same name in stanford_mrc
3. Ensure that site title lockup is spanning 2/3 and search is spanning 1/3 and that they are inline with one another
- MRC
- stanford_basic
- https://stanfordits.atlassian.net/browse/MRCD8-270
- https://github.com/SU-HSDO/stanford_mrc/pull/83

MRCD8-270 updated site title and search wrapper classes

---

templates/html.html.twig
templates/page.html.twig

- Fixed Skip nav link
- Whenever you can
- low
1. Checkout this branch
2. clear cache
3. tab to the skip nav and hit enter
4. validate it goes to the main content region of the page.

MRCD8-303 Fixed skip nav link

---

templates/components/global-footer.html.twig

- GDRP Links
- Maybe later we can make this more dynamic by use of a config.
- FRIDAY
- HIGH
1. checkout this branch
2. clear caches
3. validate new links are in the footer.
- MRC

updated footer links for GDRP & translate the text

---

stanford_basic.theme
templates/block/block--system-branding-block.html.twig
theme-settings.php

- Add additional lines in the theme settings to allow for more flexible lockups.
- When you can
- low
1. Checkout this branch
1. clear cache
1. go into the theme settings
1. add some text to the lockup settings
1. save and view result on the front end.
Styling will still be needed.

 HSD8-89 Add additional lines in the lockup

---

stanford_basic.theme

- Sometimes duplicate ids slip through. lets change them to enforce uniqueness
- whenever
- low
1. Checkout this branch and clear cache
2. ensure no duplicate ids

ensure all ids are unique

---

stanford_basic.libraries.yml

update font awesome library

---

stanford_basic.libraries.yml

updated font awesome library

---

templates/components/global-footer.html.twig

- SVG already has a link. remove the link in the template.
- meh
- low

removed double link in footer

---

templates/block/block--search-form-block.html.twig

- Fixed site search template
- end of sprint 8/30
- low
1. checkout this branch
1. clear cache
1. enter text in the top search area
1. ensure it doesnt send you to a 404 page.

D8CORE-145 Site search

---

templates/block/block--system-branding-block.html.twig
tests/behat/features/brandbar.feature
tests/behat/features/globalfooter.feature
tests/behat/features/lockup.feature

- Retroactive review
- Review everything and validate tests.
- End of next sprint (Sept 28).
- Medium
**SETUP:**
1. Install `stanford_profile` and ensure stanford_basic is set as the default theme
1. Review theme-settings.php and all of the configuration including the schema  in /config
2. Review `admin/appearance/settings/stanford_basic` form and configuration options
3. Run tests `lando blt tests:behat:run -D behat.paths=${PWD}/docroot/themes/`
1. Review the overall file structure and organization for questions, comments, and concerns.
0. Review webpack.config.js file for settings and configuration
1. Run `nvm use`
2. Install npm packages `npm install`
3. Run a build `npm run build`
4. Review README.md for documentation
1. Review files in `/src/js/*` for structure formatting and …

D8CORE-144: Stanford Basic Preliminary

---

CHANGELOG.md
package-lock.json
package.json
stanford_basic.info.yml

- Release Tag
- Today
- High
1. Review code
2. Press merge
3. Release the ~hounds~ tag.

8.4.0-alpha.1

---

templates/page.html.twig

- Added anchor for skip link
- 11/6
- high
1. checkout this branch
1. clear caches
1. tab to skip link at the top of the page
1. press enter
1. focus should skip the main navigation

Added anchor for skip link

---

CHANGELOG.md
README.md
stanford_basic.info.yml

RELEASE NOTES:
```
- Alpha 2 Release
- New html element wrappers around regions in page.html.twig.
- Added css classes to node.html.twig
- Fixed issue with role='article' on <article> in node.html.twig
- Refactored and rebuilt both the primary and secondary navigations to use new multi-menu component.
- Cleanup from codeclimate linting.
- Added codeclimate and eslint files.
- Deploy and clear caches
- Nothing special.
- Big changes to navigation
- https://github.com/SU-SWS/stanford_basic/compare/8.4.0-alpha1...8.4.0-alpha.2
```

8.4.0-alpha.2

---

stanford_basic.theme
templates/html.html.twig

- Add global google analytics for acquia sites.
- 11/25
- low
1. checkout this branch & clear cache
1. on local verify that no google analytics are added.

D8CORE-59 Added global Google analytics tracker for Acquia

---

CHANGELOG.md
stanford_basic.info.yml

Please review code and punch the release.
Release notes markup provided below.
```
- D8CORE-59: Added global Google analytics tracker for Acquia (#100)
- Move everything inside canvas-wrapper and add global footer region for outside content items (#102)
- D8CORE-856 Display paragraph contextual links (#106)
- D8CORE-941: drop cap styles (#108)
- D8CORE-941: Headings and styles (#109) center caption on image & change modular-spacing calls
- Add dist/templates to @basic twig namespace.
- Deploy and clear caches
- Nothing special clear caches and carry on.
- None
- https://github.com/SU-SWS/stanford_basic/compare/8.4.0-alpha.2...8.4.0-alpha.3
```

8.4.0-alpha.3

---

stanford_basic.info.yml

So, I can't edit the info.yml file to reset the version back to dev directly, as we looked at in the meeting this afternoon, thus this PR with a single line change.

setting version back to dev

---

templates/page.html.twig

- Fixes issue with mismatched closure tag around footer
- Today if you could.
- Medium
1. Check out this branch
2. Clear cache
3. Validate html
- Basic
- D8CORE-1231

D8CORE-1231: Correct footer closure tag.

---

stanford_basic.info.yml

back to 8.x-4.1-dev

---

stanford_basic.info.yml

- Define `stable` as the base theme for forwards compatibility with Drupal 9
- June(ish)
- Low
1. Do a build of stanford_profile with this theme or use your existing site
2. Check out this branch and clear all caches
3. Validate that nothing changes
- Everything using this base theme.
- @jenbreese 
- @katrialesser 
- @boznik 

Define stable as base theme.

---

stanford_basic.theme

- Check if the menu url is routed first. Avoids errors with external links.
- asap
- high
1. create a menu link in the main menu to an external URL.
1. validate the page doesnt whitescreen

Check if the menu link is routed before checking what route

---

.circleci/config.yml
.github/auto-label.json
.github/workflows/label.yml
README.md

- We need circleCI integration with this repo.
- I added a `config.yml` file and a `.circleci` folder.
- I included the `back-to-dev` job.
- I included auto-labeling.
- 1.2.0 code freeze
- low

D8CORE-1869: Added circleci configuration

---

templates/menus/menu-local-tasks.html.twig
templates/page--user--login.html.twig

- Removed the hard coded link the in local tasks
- Added the masthead to the user login page for an escape link.
- 8/5
- high
1. checkout branch
1. clear caches.
1. validate the summary items.

D8CORE-2467 Fixed local links

---

templates/page.html.twig

- Adds `<main>` landmark
- when possible
- Not critical
1. Checkout this branch
1. Clear the cache
1. Using WAVE, you can verify that there is now a `<main>` landmark
- D8core
- JIRA ticket: https://stanfordits.atlassian.net/browse/D8CORE-1333
https://stanfordits.atlassian.net/browse/D8CORE-2444
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

D8CORE-1333: Add '<main>' landmark

---

CHANGELOG.md
UPGRADE.md
composer.json
stanford_basic.info.yml
stanford_basic.theme

- replaced deprecated service
- Moved preprocess into stanford_profile_helper since it needs to be part of a class in D9 https://github.com/SU-SWS/stanford_profile_helper/pull/50
- End of the year
- low

D9 Readiness

---

UPGRADE.md
composer.json
stanford_basic.info.yml
templates/core/field.html.twig
templates/navigation/toolbar.html.twig

- Preemptive upgrade for Drupal 9
- :shrug: 
- very low
1. try it on a d9 site.

Use stable9 for drupal9

---

composer.json
stanford_basic.info.yml

- Updated components definition for https://www.drupal.org/docs/contributed-modules/components/registering-twig-namespaces#s-old-api-in-8x-1x
- :shrug: 
- low
1. check out this branch. 
2. checkout the branch in https://github.com/SU-SWS/stanford_profile/pull/359
3. `drush cim -y`
4. `drush cr`
5. view the site and ensure there are no errors

Update components namespace for latest components version

---

templates/block/block--system-menu-block.html.twig

- Adding a url check to the skip links in the menu block. We only want it there for the publications. If a user adds the menu block to the footer we wouldn't want the skip links added. 
- Question: what if the block menu is added to the footer and it appears on the publication/ pages? Is there a better way to do this?
- 7/16/21
- Med
- Affects all the subthemes
- It is for the keyboard users
- Medium
- a11y task
1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Create some publications and taxonomy terms.
4. Navigate to to /publications/ and /publications/filter name
5. Verify you can use the tab skip links to the main content and to the secondary navigation
- https://github.com/SU-SWS/stanford_profile/pull/437
- This is a related PR but a different Jira …

D8CORE-4525: changing how the skip link works for publications.

---

stanford_basic.theme

- For the sidebar navigation on pages like /news and /events, we need `aria-current="true"` added to the link of the page the user is currently on.
- 10/6/21
- 3
- normal
1. Check out this branch
2. clear drupal caches
3. visit `/news/awards`. Verify the link in the sidebar nav labeled "Awards" has the `aria-current` attribute set to "true".  Note, that should be on the link, not the <li>.
4. visit `/events/seminar` and verify the Seminar link also has the `aria-current` attribute.
5. Same thing should be true for `/people` and `/publications` as well.
- Is there a config:export in this PR that changes the config sync directory? NO
- Does this PR impact any particular projects, products, or modules?
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful …

D8CORE-2489 - add `aria-current`

---

stanford_basic.info.yml
stanford_basic.theme

- Adds component dependency
- Needs changelog documentation

D8CORE-000: Add components module as a dependency

---

README.md
composer.json

- Apply core patch for installing with config management.
- asap
- high
1. `composer require su-sws/stanford_basic:'dev-3176625-readme as dev-8.x-5.x'`
2. `blt di -n`
3. ensure no errors.

Added core patch and some readme documentation

---

templates/node.html.twig

- Add additional message if the node is scheduled to publish in the future.
- 3/16
- medium
1. Checkout this branch
2. create a node and schedule it to publish in the future
3. verify the banner after saving says it's schedule to publish in the future.

D8CORE-5522 Adjust unpublished message on nodes that are scheduled

---

README.md

- Thought it'd be useful to put a message in the README that the theme has been consolidated into `stanford_profile` and primary development now takes place there. Feedback welcome.
- When does this need to be reviewed by?
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?
- How urgent is this? (Normal, High)
1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...
- Is there a config:export in this PR that changes the config sync directory?
- Does this PR impact any particular projects, products, or modules?
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., …

Updated readme with consolidation info.
